[project]
name = "compmath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqt6>=6.10.0",
    "pyqtgraph>=0.13.7",
    "scipy>=1.16.3",
]
